[FEAT]: 여백을 추가하였습니다.
FUBAR-ORG/INVAIZ-Design-System pull request #71
Opened 2022-08-03 03:48 UTC by ckdwns9121

## 개요 🔍

- close #41 

## 작업 내용 📝
- 여백을 추가하였습니다.

## 기타 사항 🙋‍♂️
- 컨벤션 문서에 오타가 있어 따로 브런치를 생성하지 않고 바로 수정했습니다.

2022-08-05 15:39 UTC, IRONAGE-Park requested changes

2022-08-05 15:39 UTC, IRONAGE-Park commented on src/themes/whiteSpace.ts
> +};
이 여백을 EMotion의 `theme`에서 접근할 수 있도록 해야할 것 같습니다.

2022-08-28 08:05 UTC, IRONAGE-Park approved these changes
LGTM

2022-09-03 09:27 UTC, rlawdgus approved these changes

2022-09-03 09:34 UTC, rlawdgus commented
고생하셨습니다.

2022-09-04 05:53 UTC, merged